### ISSUE TITLE
[bug-16] 처음에 곳 등록할 때 카드 반영이 안됨

### ISSUE THREAD

**Issue by BOMS2** [YAPP-16th/Team_iOS_1_Client#185]
앱 처음 시작할 때 곳 추가하고 바로 카드 반영이 안됨 
다른 탭 들어갔다가 와야지 생성되어있음

**Comment by chelwoong** [comment]
VC의 gotList가 업데이트 될 때 cardCollectionView를 reload 시켜주면 해결되는 것 같은데,
근본적인 해결책은 아님
