### ISSUE TITLE
[frontend- 32] 알림탭 UI 구현

### ISSUE THREAD

**Issue by BOMS2** [YAPP-16th/Team_iOS_1_Client#94]
[알림탭 UI 구현]

**Comment by chelwoong** [comment]
arrive, leave cell을 따로 만들었음.
AlarmViewModel에서 우선 임시로 got을 만들고 got을 전달해서 데이터가 보여지게 했는데 최선인지 모르겠음.
Section을 어떻게 구분지을지도 생각해봐야함.

모델이 제대로 정의되면 태그색까지 설정해야하고
현재 시간 기준으로 얼마 전인지 계산하는 코드를 추가해야 함.
